spring:
  datasource:
    url: jdbc:mysql://localhost:3306/session_site?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: abcd1234

  jpa:
    hibernate:
      ddl_auto: create
    properties:
      hibernate:
        format_sql: true


  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace